### ISSUE TITLE
Recording question does not start (mic initialization issue)?

### ISSUE THREAD

**Issue by linkosal** [Azure-Samples/aisearch-openai-rag-audio#11]
I installed the application and run it in VS Code. The backend and frontend start, but when I click the "microphone" button, I get "changing columns" -animation next to the text "Conversion in progress" - from screenshots I assume that there should be a red dot. Seems like my microphone fails to initialize. How could I debug this?
![image](https://github.com/user-attachments/assets/2e2d0965-15c9-41d1-b767-32b8beca128d)

**Comment by chuwik** [comment]
The screenshots are outdated, the bars animation is the latest committed UI.

You should see a 'red circle icon' in your browser tab title if you accepted the popup to enable microphone access to the browser, that'd indicate that your microphone is being used. One way to ensure that your audio data is being sent, is opening the dev tools / network tab, and inspecting the websockets connection; you should see many messages with base64 strings from your mic audio.

**Comment by linkosal** [comment]
Thanks. Looks like the issue was with the browser, I did not get it wirk on Firefox. Chrome is better!
