### ISSUE TITLE
Add guidance for region deployment

### ISSUE THREAD

**Issue by tvriesde** [Azure-Samples/aisearch-openai-rag-audio#15]
Hi team, it could be helpful to add a couple of regional options for this solution.

gpt-4o-realtime-preview and the semantic ranker are not available in all regions. what region would be preferred for users to deploy the resources?

**Comment by iMicknl** [comment]
This repository doesn't contain infra as code, so I wonder what you are specifically looking for. Is this a request to have better documentation in this repository? 

To answer your question;
- GPT-4o-realtime-preview is available for global deployments in [East US 2 and Sweden Central regions](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#global-standard-model-availability), more information can be found [here](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/audio-real-time?pivots=programming-language-ai-studio#supported-models).

- You can leverage the [Azure AI Search regions list](https://learn.microsoft.com/en-us/azure/search/search-region-support) to understand if your region of choice supports semantic ranker. For Europe this would be North Europe or France Central for example. Please note that semantic ranker is not required for this accelerator, but might provide more relevant search results.

**Comment by tvriesde** [comment]
Hi mick, yes that answers my question. 

The README mentions prerequisites for service deployment. But it was not clear from the README in what regions those services need to be deployed to support the application.
