### ISSUE TITLE
Using the code with existing LLM deployment

### ISSUE THREAD

**Issue by linkosal** [Azure-Samples/aisearch-openai-rag-audio#23]
When I run the command "azd up", it tries to establish a new resource group, including a new deployment of the LLM. I already have an existing deployment, so the command fails to create a new one (exceeding quota). How should I modify the script to use the existing deployment?

**Comment by pamelafox** [comment]
@linkosal I'm working on making it so you can bring your own resources. For now, you could remove the openai module in main.bicep, and make sure to set the AZURE_OPENAI_ENDPOINT and _DEPLOYMENT variables, i.e. change:

      AZURE_OPENAI_ENDPOINT: openAi.outputs.endpoint
      AZURE_OPENAI_REALTIME_DEPLOYMENT: openAiDeployments[0].name

You'd also need to make sure the Container App has the role to be able to use the OpenAI resource (openAiRoleBackend in main.bicep)

**Comment by linkosal** [comment]
I removed the openai -module and hard-coded the openai variables to point to my existing deployment. But now 'azd up' crashes while trying to deploy 'aca-web'. It seems that it parses incorrectly the property 'registries.server', after I replaced the 'AZURE_OPENAI_ENDPOINT:' found in module acaBackend with a  hard-coded value pointing to my existing AI model endpoint.

**Comment by pamelafox** [comment]
My PR here adds docs and parameters for bringing in your own OpenAI deployments, does this work for you?
https://github.com/Azure-Samples/aisearch-openai-rag-audio/pull/27

**Comment by linkosal** [comment]
Thanks, I'll check this next week.



-Tapio-


[cid:0f1e8fd3-f181-48a5-aa7b-a854543616c0]
Tapio Linkosalo | Data Scientist | Data & Analytics

Innofactor Plc | Keilaranta 9, FI-02150 Espoo, Finland
+358 40 517 0571 | ***@***.******@***.***> | https://www.linkedin.com/in/tapio-linkosalo/
www.innofactor.com<http://www.innofactor.com/>

________________________________
