### ISSUE TITLE
c# version with real time api

### ISSUE THREAD

**Issue by giannik** [Azure-Samples/aisearch-openai-rag-audio#32]
I'm looking to convert this  To C# Instead of Python. The most challenging part seems to be the real time implementation located in this file. 

https://github.com/Azure-Samples/aisearch-openai-rag-audio/blob/main/app/backend/rtmt.py

Do you think it would be possible to convert these 2 C# and perhaps use signalR for the websocket functionality?

**Comment by pamelafox** [comment]
There is already a fork in the works for C#, so you could wait for that. @pablocastro is working on it. Am not sure what Pablo is using instead there.

**Comment by pamelafox** [comment]
Marking as duplicate of https://github.com/Azure-Samples/aisearch-openai-rag-audio/issues/12
