### ISSUE TITLE
Choosing the voice for application?

### ISSUE THREAD

**Issue by linkosal** [Azure-Samples/aisearch-openai-rag-audio#33]
Is it possible to choose the voice that the application uses? AI Studio gives three options ( Alloy / Echo / Shimmer ), how to I make my app talk in "shimmer" voice?

**Comment by pamelafox** [comment]
Yes, see this PR for how to do it: https://github.com/Azure-Samples/aisearch-openai-rag-audio/pull/20

**Comment by ville022** [comment]
Hello, tried the change as described PR #20 - no change in the voice produced, however. Please advice

**Comment by olivMertens** [comment]
what is the voice you have chosen ? same thing with the 6 possibilities of voice ? @ville022

**Comment by pamelafox** [comment]
I also am unable to hear a different in voice choice. I'm asking around to see if our voice choice is more limited on Azure.

**Comment by olivMertens** [comment]
i verified the pr Works , only 3 voice are available for azure open ai 
Check #20 updated

**Comment by ville022** [comment]
Interested to hear if and when all 6 voices are truly available. I can verify testing via Azure AI Studio that in the playground for the same model the voice parameter (dropdown) also includes only three voices.

**Comment by pamelafox** [comment]
We've now merged the PR from @olivMertens, pull the latest main and follow https://github.com/Azure-Samples/aisearch-openai-rag-audio/blob/main/docs/customizing_deploy.md to customize the voice choice. I haven't heard anything about when all 6 choices will be available.
