### ISSUE TITLE
Using Quart framework

### ISSUE THREAD

**Issue by madhubandru** [Azure-Samples/aisearch-openai-rag-audio#36]
Can the **quart** framework be used in place of aiohttp in this accelerator? Will there be any compatibility issues?

I am considering using azure openai real-time audio in my existing quart application.

Any references would be greatly appreciated.

**Comment by pamelafox** [comment]
I would assume so, since quart does have support for websockets, as detailed here:
https://quart.palletsprojects.com/en/latest/how_to_guides/websockets.html

@pablocastro Was there a particular reason for aiohttp / did you try other frameworks and encounter issues?

**Comment by pablocastro** [comment]
No particular reason, aiohttp just did everything we needed, including both client- and server-side websockets, and it's easy to use. I haven't used Quart, but it looks like it has websockets support so it should be fine, though on quick look I didn't see it has a websocket client, if it indeed doesn't have one you'll need to use something else.

**Comment by pamelafox** [comment]
Okay, thanks @pablocastro for the explanation. I'm closing this since we're not planning to port this to Quart in the main repo, but @madhubandru please share your code in a gist/fork if you end up using it, as other folks may be interested.
