### ISSUE TITLE
'chunk_id' is not a filterable field

### ISSUE THREAD

**Issue by kirkhofer** [Azure-Samples/aisearch-openai-rag-audio#4]
If you add an index by just running the `import and vectorize data` the `chunk_id` field is not marked as `filterable`. Even though the application launches, you receive errors because the code for `ragtools.py` is trying to filter on the `chunk_id` field. The app just doesn't work as expected even though you can have a conversation it doesn't see the index at all.

![image](https://github.com/user-attachments/assets/1a177549-ede3-4dd0-af24-4878580fdccc)

**Comment by pablocastro** [comment]
Good catch, I forgot we just changed this to use less resources, all my existing test indexes had this enabled. Will fix this shortly to avoid needing chunk_id to be filterable.

**Comment by pablocastro** [comment]
Fixed in fad1672257091fcf3aa83a013892047e71229999
